import React from "react";
import { Idioma } from "../types";
interface Entry { id:string; institution:string; degree:string; period:string; description?:string }
const EducationSection: React.FC<{education:Entry[]; idiomas:Idioma[]}> = ({education,idiomas}) => <section id="formacao" className="relative py-28 md:py-36"><div className="section-shell">
 <div className="grid lg:grid-cols-[.8fr_1.2fr] gap-10 items-end mb-14"><div><span className="section-kicker">Formação</span><h2 className="section-title">Base para construir <span className="text-primary-gradient">profundidade.</span></h2></div><p className="section-copy mt-0">Formação técnica industrial, graduação em andamento e especializações complementares em tecnologia.</p></div>
 <div className="grid lg:grid-cols-12 gap-5"><div className="lg:col-span-8 space-y-3">{education.map((e,i)=><article key={e.id} className="glass-morphism rounded-2xl p-6 hover-lift"><div className="flex gap-5"><span className="font-mono text-xs text-orange-400 pt-1">{String(i+1).padStart(2,"0")}</span><div className="flex-1"><div className="flex flex-wrap justify-between gap-3"><span className="eyebrow">{e.period}</span><span className="eyebrow">{e.institution}</span></div><h3 className="mt-3 text-base md:text-lg font-extrabold text-white">{e.degree}</h3>{e.description&&<p className="mt-2 text-sm leading-6 text-slate-500">{e.description}</p>}</div></div></article>)}</div>
 <aside className="lg:col-span-4 glass-morphism rounded-3xl p-7 md:p-8"><span className="section-kicker">Idiomas</span><div className="mt-8 space-y-7">{idiomas.map(i=><div key={i.name}><div className="flex justify-between"><span className="font-bold text-white text-sm">{i.name}</span><span className="font-mono text-xs text-orange-400">{i.proficiency}%</span></div><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">{i.category}</p><div className="mt-3 h-1 bg-white/5 rounded-full"><div className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-300" style={{width:`${i.proficiency}%`}}/></div></div>)}</div><div className="mt-10 pt-7 border-t border-white/10"><span className="eyebrow">Direção</span><p className="mt-3 text-sm leading-6 text-slate-300">Especialização progressiva em <span className="text-white font-semibold">planejamento, tubulações e sistemas industriais.</span></p></div></aside></div>
 </div></section>;
export default React.memo(EducationSection);
